export const CANVAS_SCALE_INCREASING_DIRECTION = +1;
export const CANVAS_SCALE_DECREASING_DIRECTION = -1;
export const CANVAS_SCALE_NO_CHANGES_OF_DIRECTION = 0;

export type ScaleDirection =
  | typeof CANVAS_SCALE_INCREASING_DIRECTION
  | typeof CANVAS_SCALE_DECREASING_DIRECTION
  | typeof CANVAS_SCALE_NO_CHANGES_OF_DIRECTION;
